HOST = '127.0.0.1'
DB = 'pokedex'
USER = 'root'
PASSWORD = '**********'
DEBUG = True

# #####POKEMONS######
SPAWN_RATIO_RARITY_VERY_COMMON = .009
SPAWN_RATIO_RARITY_COMMON = .004
SPAWN_RATIO_RARITY_UNCOMMON = .002
SPAWN_RATIO_RARITY_RARE = .001
SPAWN_RATIO_RARITY_VERY_RARE = .0009
SPAWN_RATIO_RARITY_SPECIAL = .0008
SPAWN_RATIO_RARITY_EPIC = .0005
SPAWN_RATIO_RARITY_LEGENDARY = .0001
SPAWN_RATIO_EGG = .01

# #####GLOBALS######
TIME_BETWEEN_HUNTING = .3
POKEBALL_CATCH_CHANCE = .1
EGG_HATCH_TIME = 5
